export const pricesList = [
  {
    prices: [
      {
        id: 1,
        title: '1 - 4 personnes',
        desc: 'Best option for personal use & for your next project.',
        price: '$0',
        priceList: { month: 25, trimestre: 72.5, semestre: 142.5, year: 270 },
        list: [
          'Consultation sur demande ',
          'Visite à Domicile de suivi ',
          '1 Consultation Super Spéciale & spécifique par trimestre',
          'Services Promotion & prévention',
          'Télémédecine (50% des frais payé par CRESAMEF)',
        ],
      },
      {
        id: 2,
        title: '5 - 8 personnes',
        desc: 'Best option for personal use & for your next project.',
        price: '$20',
        priceList: { month: 35, trimestre: 101.5, semestre: 199.5, year: 378 },
        list: [
          'Consultation sur demande ',
          'Visite à Domicile de suivi ',
          '1 Consultation Super Spéciale & spécifique par trimestre',
          'Services Promotion & prévention',
          'Télémédecine (50% des frais payé par CRESAMEF)',
        ],
      },
      {
        id: 3,
        title: '9 - 12 personnes',
        desc: 'Best option for personal use & for your next project.',
        price: '$40',
        priceList: { month: 35, trimestre: 101.5, semestre: 199.5, year: 378 },
        list: [
          'Consultation sur demande ',
          'Visite à Domicile de suivi ',
          '1 Consultation Super Spéciale & spécifique par trimestre',
          'Services Promotion & prévention',
          'Télémédecine (50% des frais payé par CRESAMEF)',
        ],
      },
      {
        id: 4,
        title: '13 - 15 personnes',
        desc: 'Best option for personal use & for your next project.',
        price: '$100',
        priceList: { month: 45, trimestre: 130.5, semestre: 256.5, year: 486 },
        list: [
          'Consultation sur demande ',
          'Visite à Domicile de suivi ',
          '1 Consultation Super Spéciale & spécifique par trimestre',
          'Services Promotion & prévention',
          'Télémédecine (50% des frais payé par CRESAMEF)',
        ],
      },
    ],
    name: 'JAMA A',
  },
  {
    prices: [
      {
        id: 1,
        title: '1 - 4 personnes',
        desc: 'Best option for personal use & for your next project.',
        price: '$0',
        priceList: { month: 10, trimestre: 29, semestre: 57, year: 108 },
        list: [
          'Consultation sur demande ',
          'Visite à Domicile de suivi ',
          '1 Consultation Super Spéciale & spécifique par trimestre',
          'Services Promotion & prévention',
          'Télémédecine (50% des frais payé par CRESAMEF)',
        ],
      },
      {
        id: 2,
        title: '5 - 8 personnes',
        desc: 'Best option for personal use & for your next project.',
        price: '$0',
        priceList: { month: 20, trimestre: 58, semestre: 114, year: 216 },
        list: [
          'Consultation sur demande ',
          'Visite à Domicile de suivi ',
          '1 Consultation Super Spéciale & spécifique par trimestre',
          'Services Promotion & prévention',
          'Télémédecine (50% des frais payé par CRESAMEF)',
        ],
      },
      {
        id: 3,
        title: '9 - 12 personnes',
        desc: 'Best option for personal use & for your next project.',
        price: '$0',
        priceList: { month: 30, trimestre: 87, semestre: 171, year: 324 },
        list: [
          'Consultation sur demande ',
          'Visite à Domicile de suivi ',
          '1 Consultation Super Spéciale & spécifique par trimestre',
          'Services Promotion & prévention',
          'Télémédecine (50% des frais payé par CRESAMEF)',
        ],
      },
      {
        id: 4,
        title: '13 - 15 personnes',
        desc: 'Best option for personal use & for your next project.',
        price: '$0',
        priceList: { month: 40, trimestre: 116, semestre: 228, year: 432 },
        list: [
          'Consultation sur demande ',
          'Visite à Domicile de suivi ',
          '1 Consultation Super Spéciale & spécifique par trimestre',
          'Services Promotion & prévention',
          'Télémédecine (50% des frais payé par CRESAMEF)',
        ],
      },
    ],
    name: 'JAMA B',
  },
  {
    prices: [
      {
        id: 1,
        title: 'AFIA 1',
        desc: 'Best option for personal use & for your next project.',
        price: '$0',
        priceList: {
          month: '$50',
          trimestre: '$145',
          semestre: '$285',
          annee: '$540',
        },
        list: [
          'Paquet JAMA +',
          'Check-up santé (bilan de santé)',
          '1 evacuations par ambulance/an. Au delà de ce quota, 75% des frais sera à la charge du client',
          'Prélèvement à domicile',
          'Livraison des médicaments à domicile',
          'Hospitalisation à Domicile',
          '1 consultation à Domicile en dehors de Goma/mois',
          'Facilitation de tourisme médical & évacuation à l’étranger ( Le client paye les frais de commission avec une réduction de 10% coût relatif au voyage )',
          'Accompagnement médical avec 25% des frais et le billet retour pour le medecin prise en charge par CRESAMEF',
        ],
      },
      {
        id: 2,
        title: 'AFIA 2',
        desc: 'Best option for personal use & for your next project.',
        price: '$20',
        priceList: {
          month: '$75',
          trimestre: '$217.5',
          semestre: '$427.5',
          annee: '$810',
        },
        list: [
          'Paquet JAMA +',
          'Check-up santé (bilan de santé)',
          '1 evacuations par ambulance/an. Au delà de ce quota, 75% des frais sera à la charge du client',
          'Prélèvement à domicile',
          'Livraison des médicaments à domicile',
          'Hospitalisation à Domicile',
          '1 consultation à Domicile en dehors de Goma/mois',
          'Facilitation de tourisme médical & évacuation à l’étranger ( Le client paye les frais de commission avec une réduction de 10% coût relatif au voyage )',
          'Accompagnement médical avec 25% des frais et le billet retour pour le medecin prise en charge par CRESAMEF',
        ],
      },
      {
        id: 4,
        title: 'AFIA 3',
        desc: 'Best option for personal use & for your next project.',
        price: '$100',
        priceList: {
          month: '$100',
          trimestre: '$290',
          semestre: '$570',
          annee: '$1080',
        },
        list: [
          'Paquet JAMA +',
          'Check-up santé (bilan de santé) ',
          '2 evacuations par ambulance/an. Au delà de ce quota, 50% des frais sera à la charge du client',
          'Prélèvement à domicile',
          'Livraison des médicaments à domicile',
          'Hospitalisation à Domicile',
          '1 consultation à Domicile en dehors de Goma/mois',
          'Facilitation de tourisme médical & évacuation à l’étranger ( Le client paye les frais de commission avec une réduction de 15% coût relatif au voyage )',
          'Accompagnement médical avec 25% des frais et le billet retour pour le medecin prise en charge par CRESAMEF',
        ],
      },
    ],
    name: 'AFIA ',
  },
  {
    prices: [
      {
        id: 1,
        title: 'VIP /2',
        desc: 'Best option for personal use & for your next project.',
        price: '$0',
        priceList: {
          month: '$150',
          trimestre: '$435',
          semestre: '$855',
          annee: '$1620',
        },
        list: [
          'Paquet AFIA +',
          'Visite à domicile (VAD) mensuel systématique ',
          '4 evacuations par ambulance/an. Au delà de ce quota, 50% des frais sera à la charge du client',
          'Facilitation de tourisme médical & évacuation à l’étranger ( Le client paye les frais de commission avec une réduction de 25% coût relatif au voyage )',
          'Gardiennage médical (le client s’occupera juste de la restauration du gardien)',
          'Accompagnement d’un malade à Bukavu (50% des frais de voyage pour CRESAMEF)',
          'Accompagnement d’un malade à Kinshasa & Lubumbashi  (50% des honoraires pour CRESAMEF)',
          'Accompagnement d’un malade à Gisenyi (50% des frais de documents pour CRESAMEF)',
          'Accompagnement d’un malade à Kigali et Bujumbura  (50% des frais de documents pour CRESAMEF)',
        ],
      },
      {
        id: 2,
        title: 'VIP',
        desc: 'Best option for personal use & for your next project.',
        price: '$20',
        priceList: {
          month: '$200',
          trimestre: '$580',
          semestre: '$1140',
          annee: '$2160',
        },
        list: [
          'Paquet AFIA +',
          'Visite à domicile (VAD) mensuel systématique ',
          '12 evacuations par ambulance/an. Au delà de ce quota, 50% des frais sera à la charge du client',
          'Facilitation de tourisme médical & évacuation à l’étranger ( Le client paye les frais de commission avec une réduction de 50% coût relatif au voyage )',
          'Gardiennage médical (le client s’occupera juste de la restauration du gardien)',
          'Accompagnement d’un malade à Bukavu (100% des frais de voyage pour CRESAMEF)',
          'Accompagnement d’un malade à Kinshasa & Lubumbashi  (100% des honoraires pour CRESAMEF)',
          'Accompagnement d’un malade à Gisenyi (100% des frais de documents pour CRESAMEF)',
          'Accompagnement d’un malade à Kigali et Bujumbura  (100% des frais de documents pour CRESAMEF)',
        ],
      },
      {
        id: 4,
        title: 'VIP +',
        desc: 'Best option for personal use & for your next project.',
        price: '$100',
        priceList: {
          month: '$250',
          trimestre: '$725',
          semestre: '$1425',
          annee: '$2700',
        },
        list: [
          'Paquet AFIA +',
          'Visite à domicile (VAD) mensuel systématique ',
          '12 evacuations par ambulance/an',
          'Facilitation de tourisme médical & évacuation à l’étranger ( Aucun frais de commission )',
          'Gardiennage médical (le client s’occupera juste de la restauration du gardien)',
          'Accompagnement d’un malade à Bukavu (100% des frais de voyage pour CRESAMEF)',
          'Accompagnement d’un malade à Kinshasa & Lubumbashi  (100% des honoraires pour CRESAMEF)',
          'Accompagnement d’un malade à Gisenyi (100% des frais de documents pour CRESAMEF)',
          'Accompagnement d’un malade à Kigali et Bujumbura  (100% des frais de documents pour CRESAMEF)',
          'Achat médicaments (50% des spécialités sera pris en charge par CRESAMEF 1 fois/mois)',
        ],
      },
    ],
    name: 'VIP',
  },
];
